--- 
- hosts: all 
  become: yes 
  tasks: 

        - name: i want to install webserver
          apt: 
              name: apache2 
              state: present
          when: ansible_os_family="Debian"

        - name: i want to start/stop on ubuntu
          service: 
               name: apache2
               state: started
          when: ansible_os_family="Debian"

        - name: i want to install webserver on RedHat
          yum:
                name: htttpd
                state: started
          when: ansible_os_family="RedHat"

        - name: i want to start/stop on webserver on RedHat
          service:
                 name: htttpd
                 state: started
          when: ansible_os_family="RedHat"       